# Generated by Django 5.1.3 on 2024-12-07 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceapp', '0002_user_delete_face_remove_video_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='original_video',
            field=models.FileField(default='default_video.mp4', upload_to='before/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='processed_video',
            field=models.FileField(blank=True, null=True, upload_to='after/'),
        ),
        migrations.CreateModel(
            name='FaceRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video')], default='photo', max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to='face/before_regis/')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='faceapp.user')),
            ],
        ),
    ]
